package main

import (
	"log"

	"github.com/yeqown/micro-server-demo/global"
	"github.com/yeqown/micro-server-demo/internal/model"
	"github.com/yeqown/micro-server-demo/internal/repository"
	_grpc "github.com/yeqown/micro-server-demo/internal/server/grpc"

	"github.com/urfave/cli"
	"github.com/yeqown/infrastructure/framework/gormic"
)

func getAutoGenerateDBCommand() cli.Command {
	dbConn, err := gormic.ConnectMysql(global.GetConfig().Mysql)
	if err != nil {
		panic(err)
	}

	return cli.Command{
		Name:  "generate",
		Usage: "auto generate DB tables",
		Action: func(c *cli.Context) error {
			dbConn.AutoMigrate(
				&model.FooModel{},
				// more...
			)
			return nil
		},
	}
}

func getStartServerCommand() cli.Command {
	dbConn, err := gormic.ConnectMysql(global.GetConfig().Mysql)
	if err != nil {
		panic(err)
	}
	fooRepo := repository.NewFooRepo(dbConn)

	return cli.Command{
		Name:  "start",
		Usage: "starting REST and GRPC servers",
		Flags: []cli.Flag{
			cli.IntFlag{
				Name:  "rpcPort",
				Value: 8080,
				Usage: "rpc server port",
			},
			cli.IntFlag{
				Name:  "httpPort",
				Value: 8081,
				Usage: "http server port",
			},
		},
		Action: func(c *cli.Context) error {
			rpcPort := c.Int("rpcPort")
			_grpcSrv := _grpc.New(fooRepo, rpcPort)
			log.Printf("running gRPC server on: %d\n", rpcPort)
			return _grpcSrv.Run()
		},
	}
}
